### ISSUE TITLE
API文書の更新

### ISSUE THREAD

**Issue by ide-an** [android-spa-titech/HQTP#101]
サーバー側の仕様の更新にwikiのAPIのページが追いついてないので書く。

**Comment by ide-an** [comment]
APIドキュメント更新しました。
wiki historyの[47fc1a2]から[8a8aa52]まで。

@cloverrose 
暇な時でいいので、抜けがあるかどうかチェックお願いします。

**Comment by ide-an** [comment]
チェック確認しました。

**Comment by draftcode** [comment]
OKですかね。Closeします。
