### ISSUE TITLE
アプリ連携取り消しを行った際のconsumer_info.pyの更新を自動化

### ISSUE THREAD

**Issue by cloverrose** [android-spa-titech/HQTP#103]
アプリ連携を取り消すと、アクセストークン・シークレットが変更される。
consumer_info.py内に保存している内容を更新しないと次回以降テストが失敗する
この処理を自動化する
（どうやってやるか疑問）

また、テストとしてアプリ連携を取り消して再認証した場合もテストを記述する
（どうやって連携取り消しを実装するのかが肝）

よって、以上のissueが完了するまで、サーバーサイドのテストがめんどくさいので、
android_spaのアプリ連携の取り消しをしないでください。

**Comment by draftcode** [comment]
あー。なるほど。そういう影響があるのかー。上手くtweepyのモックを作ってやると、そういう依存性をなくせそうだけど、面倒くさそうですね。

**Comment by cloverrose** [comment]
その手があったか

**Comment by cloverrose** [comment]
#91 と関連するのでそのまま91-serverで実装しました

**Comment by cloverrose** [comment]
とりあえずTweepyのモックを作って対処。
python manage.py test実行時と
python manage.py shell/runserver実行時で挙動を変えることでサーバー側でテストするときは
常にconsumer_info.pyに保存している情報が正しいものと判定されます。

クライアントとの連携部分は実際にTwitterにアクセスすることで適切に動くはず。
注意点として今後認証部分のテストが、shellのコピペではうまくいかない場合が有る
