### ISSUE TITLE
役割分担の図的なものを作る

### ISSUE THREAD

**Issue by draftcode** [android-spa-titech/HQTP#105]
どういうものを作るのかよくわかっていませんが、サーバーサイドとかクライアントサイドとかUX担当とかリーダーとかのグループに分かれて作業していますとかの図が欲しいです。テキトーに作ってみてください。よろしくおねがいします。

**Comment by cloverrose** [comment]
うーん、サブチームに分かれて作業してますっていう大枠や
リーダーやide-anさんの仕事内容やサーバーサイド内の役割分担はおおよそ把握できてるんですが、
クライアントサイドとUXはサイドでの役割がどうなっているかイマイチ把握できていません。

@ide-an 
クライアントサイドでの役割分担が現状どうなっているのか簡単に教えて下さい。

 @hiroqn @Biacco42 
UXサイドでの役割分担がどうなっているのか、また担うべき範囲というのもいまいちわかっていないので
おおまかに説明がほしいです

現時点での役割を明確にすることは重要だと思うのでよろしくお願いします。

**Comment by cloverrose** [comment]
自分が把握している役割を列挙したものを
Dropboxの2012-07-04フォルダにあげておきました。

空白部分を埋めたいのでお願いします

**Comment by ide-an** [comment]
クライアントサイドは自分と@nkbswくんで分担してコーディング / レビューしてる感じです。まだあんまり分担振れてないけど。
@draftcodeくんにもテスト関連を中心に書いてもらってます。

**Comment by draftcode** [comment]
@cloverrose 
役割分担図、今上がっているやつでOKですかね?

**Comment by cloverrose** [comment]
@draftcode
OKです。レイアウトは適宜変更しちゃってください

**Comment by draftcode** [comment]
@cloverrose
了解です。Closeしますね。
