### ISSUE TITLE
要件をもう少し文章でまとめる

### ISSUE THREAD

**Issue by draftcode** [android-spa-titech/HQTP#107]
Wikiの要求仕様でちょろっと書いた気もしますが、7/4にチームでこんなアプリにして行きましょうという感じで話したことを、ちょっとした文章でまとめてみてください。そこからピックアップしてスライドを作って話してみます。よろしくおねがいします。

**Comment by ide-an** [comment]
とりあえず要件をテキストに起こしてみました。

#大
- ゲーミフィケーションを通して大学生の授業を楽しくする
- 講義を行う教員へのフィードバックを実現する

#中
- ユーザー同士で質問を投げ合えるサービス
- 講義ごとにチャットルームが作られ、そこに投稿するようなイメージ
- チャットルームの中で質問を投げるほか講義ノートの共有もできる
- 学生同士のみでも成立するサービス。教員が講義ノートを提供するなど積極的に参加するとなお良い
- サービス内での様々な活動に対して実績システムを導入し、利用者の講義に対するモチベーションを上げる

#小
- 講義の各時限ごとにチャットルームが作られる。
- 講義中は通常その時限のチャットルームに投稿する
- 過去の時限のチャットルームに投稿する事もできる
- チャットルームの時間軸は「投稿時間」ではなく「投稿したい時間」
  - 投稿するときに授業中のどの時間に投稿するかを選べる
  - これによって授業中のどのポイントに対する質問/発言なのかを指定できる
- チャットルームの開始/終了をどのように決めるかは検討中
  - 教員でないユーザーが勝手に決めていいかどうか
  - 開始から終了までの時間を決めるか否か
- 実績はプラス評価の活動にもマイナス評価の活動にもどうでも良い活動にも提供される
  - 授業サボる→マイナス評価トロフィー貰う→ぐぬぬ感！！！
- 取得した実績はトロフィーとしてクライアントから一覧を見れる

**Comment by ide-an** [comment]
ボタンの話が抜けているのはそもそも要件に含まれているかどうかよく分からなかったからです。
前回の話し合いではこの話が抜けてたかなと思っています。

**Comment by draftcode** [comment]
@ide-an 
取り入れてスライド作ってみました。Dropbox/Android-Spa/MidtermAnnouncementのPDFを見てみてください。

ボタンはどうなんでしょうね。:thumbsup: と :thumbsdown: を各投稿に入れるという形で十分になるんでしょうか。

**Comment by ide-an** [comment]
ボタンについては話し合いの機会が欲しいですね。

要件についてですが、

```
チャットルームの時間軸は「投稿時間」ではなく「投稿したい時間」
```

個人的にはこの仕様はある種キモになりそうな気がしています。
再検討後の要件の1つとして主張してもいいんじゃないかと思います。

**Comment by draftcode** [comment]
スライドに要件追加してみました。少し体裁を変えて、要求仕様に移行しました。

https://github.com/android-spa-titech/HQTP/wiki/Requirements

このIssueはCloseします。要件については上のページへ、スライドについては #109 へお願いします。
