### ISSUE TITLE
作るアプリのスケッチのようなものを描く

### ISSUE THREAD

**Issue by draftcode** [android-spa-titech/HQTP#108]
スライドで、こういう感じのアプリケーションを作りますという説明をするのに使いたいので、講義一覧の画面と、一回の授業のタイムラインみたいな画面のスケッチが欲しいです。よろしくおねがいします。

**Comment by draftcode** [comment]
@Biacco42 @hiroqn 
どっちがどの画面を担当しましょうか?

**Comment by hiroqn** [comment]
とりあえず、講義一覧の方を書いてみます。
絵→写真,または,デジタルイラストのほうが好ましいでしょうか？、その場合ペイントになってしまいますが

**Comment by draftcode** [comment]
@hiroqn 
メディアは何でもいいですよ。紙上でもスキャンしてそれ使いますし。

**Comment by draftcode** [comment]
@hiroqn 
作ってもらったスケッチ受け取りました。Dropbox/Android-Spa/MidtermAnnouncementにあるスライドのPDFファイルにスクリーンショットを埋めてみました。確認してみてください。

あと、なぜか電話番号が入ってますが、大丈夫ですか?
