### ISSUE TITLE
作業の進め方を決める

### ISSUE THREAD

**Issue by draftcode** [android-spa-titech/HQTP#12]
どういう風に作業を分担して、成果はどういう風に確認するのか。とか、ペアプログラミング・コードレビューなども必要かもしれません。

**Comment by draftcode** [comment]
権藤先生に相談したのですが、実際に要件が決まっている状況(具体的にこの機能を実装するというのが決まっている状況)で、どのように作業を進めるのかについて、おすすめできる方法は特に無いようです。教科書的にはUMLを作ることになるようですが、嫌ですよね?

今までのアルバイトの経験からすると、既にある程度のコードができている状態で、「この機能を実装してね」と言われて、その機能を実装する。他の人も別の機能を実装したり、バグ修正したりをします。こういう状態になれれば良いんですが、最初のコードを作るところをどうしようか、というのが最近の悩みどころです。

今のところの案としては、2人コードを書く人を決めてしまって、サーバー側とクライアント側で、その場でペアプログラミングのように、何人かで画面を見ながら最初の作業を進めてしまうということを考えています。

**Comment by draftcode** [comment]
一応書いてみました。ide_an君にレビューしてもらいましょう。
https://github.com/android-spa-titech/HQTP/wiki/DevelopmentProcess

**Comment by ide-an** [comment]
追記を入れました。
https://github.com/android-spa-titech/HQTP/wiki/DevelopmentProcess/61fd75c3c01d27f33c23d5638383da0d23547f45

**Comment by draftcode** [comment]
ありがとうございます。とりあえずCloseしますね。
