### ISSUE TITLE
Djangoのテンプレートをコミットする

### ISSUE THREAD

**Issue by draftcode** [android-spa-titech/HQTP#16]

**Comment by cloverrose** [comment]
HTTPリクエストを処理するプロトタイプサーバーをコミットしました

**Comment by draftcode** [comment]
2箇所コメントしました。

https://github.com/android-spa-titech/HQTP/commit/a5ada0119090dfb9ebcebe0f401205157e4c3507#L0R110
https://github.com/android-spa-titech/HQTP/commit/2e59239eae72ee1754b5a3cda3175323da91c3c6#L3R6

あと、試しにPull Requestを送ってみても面白いかも。

**Comment by cloverrose** [comment]
Pull Requestやったことないので、とりあえず修正しておきました。
