### ISSUE TITLE
仕様書を書く

### ISSUE THREAD

**Issue by draftcode** [android-spa-titech/HQTP#18]
仕様書を
- 構造的理解
- 構文的理解
- 機能的理解

に基づいて書く。

**Comment by draftcode** [comment]
難しい…… なんで難しいかというと、書くことが決まってないからですよ! 実際何について仕様を書かなければいけないのでしょうか。何についての仕様書が必要なんでしょうか。何が必要かについて聞いておきたいです。

一旦Assignmentを外して、次回集まったときに、なんの仕様書が欲しいのかについて話しあいましょう。

**Comment by draftcode** [comment]
アプリがどういう機能を実装していくのか、どういうコンセプトなのかを書けば良いのかな?

**Comment by draftcode** [comment]
OK、最低限、要求仕様までは書くようにしましょうか。

**Comment by cloverrose** [comment]
Wikiの23番「投稿画面で、タイトルと本文を入力して、投稿ボタンを押して、質問を投稿できた場合、メイン画面に遷移すること。」は投稿一覧画面で自分の投稿が反映されているか絶対見るし、だれかが反応してくれないか気になると思うので、
一覧画面（今後質問ごとのスレッド機能が実装されるならその画面）に遷移したほうがよくないですか？

**Comment by draftcode** [comment]
@cloverrose 
ありがとうございます。なるほど、投稿一覧画面に遷移した方が良さそうですね。修正しました。

**Comment by hiroqn** [comment]
よいように思います。
- 各マイルストーンの最初にこのようなチェックリストを作っておくことの有効性

ある程度ならあったほうがいいと思います。
しかし、細かすぎると、プログラムするヒトの感性を損ねるように思います。
- このようなチェックリストから、具体的な作業に落とす場合の格差

結局使用要求の粒度次第ですよね。あとこれってTDDにはいるんですかね？

**Comment by draftcode** [comment]
@hiroqn 

ありがとうございます。

> 細かすぎると、プログラムするヒトの感性を損ねるように思います。

なるほど、そういう影響もありそうですね。自分としては、「コレが全部できたら終了」という指標として使いたいという意図がありました。

> あとこれってTDDにはいるんですかね？

これはTDDじゃないですね。TDDの前のステップだと思います。ここら辺の要求仕様の話とか、TDDに興味があれば、本お貸ししますよ。(そしてきっとあなたもアンチTDDになれるはず!)

**Comment by draftcode** [comment]
投稿するときに、タイトルか本文かが空白だったらダメというのは、仕様に入れるべきですかね？

**Comment by nkbsw** [comment]
Atamiの要求仕様リストはもう見れないみたいですが、前回見た感じだいたい必要な機能は網羅していたかと思います。
あんな感じで必要な仕様が細かく分かれていた方が作りやすくて良いと思います。

**Comment by draftcode** [comment]
@nkbsw 
ありがとうございます。Atamiの要求仕様リストは、下の方にあるタブで切り替える事が出来ます。

細かく分かれていた方が、自分が何をするべきなのか明確になるという一方で、プログラムを書く側の自由が少し失われてしまうというトレードオフがあるようですね。ただ、前回の「講義ボタンを押した後に、具体的にどのような画面が出るのか。新規のタイムラインなのか昨日までのタイムラインなのか。」のような、曖昧になってしまう部分は排除しないと、実装する側も困りそうです。

次はBeppuなので、前回の議論を元に、それっぽい仕様を書いてみようと思います。
