### ISSUE TITLE
icon_urlとしてusers/profile_image/:screen_nameを用いるのは不適

### ISSUE THREAD

**Issue by ide-an** [android-spa-titech/HQTP#180]
現状、icon_urlとしてhttps://dev.twitter.com/docs/api/1/get/users/profile_image/%3Ascreen_name のAPIを利用しているが、

```
 This method must not be used as the image source URL presented to users of your application.
```

とあるように推奨されない。(ついでに使う度にAPI消費する)
ということでget_vc()したときに得られるUserオブジェクトのprofile_image_urlを使うようにする。

**Comment by cloverrose** [comment]
@ide_an　りょうかいです　。画像保存してそのURLを渡す感じにするまでの暫定版だったからちゃんと調べてなかった。
