### ISSUE TITLE
Fixtureの自動生成スクリプト

### ISSUE THREAD

**Issue by cloverrose** [android-spa-titech/HQTP#191]

**Comment by draftcode** [comment]
Fixture自動生成とは……？

**Comment by cloverrose** [comment]
Lecture.objects.create(name='ITSP', code='12345')
という実行が行われたDBを作成→ダンプしてFixtureを作成する。

**Comment by ide-an** [comment]
railsのfixturesみたいなノリなのかなぁ。
YAMLでレコードデータを書いとくとテスト用のDBに投入される的な。

**Comment by cloverrose** [comment]
テスト用のDBに投入される用のデータを作るスクリプト。
リレーション貼ったりするとJSON・YAMLの書き方覚えないとなので、Djangoの書き方で書けるようにした

**Comment by cloverrose** [comment]
冷静に考えると遠回りなことだったので閉じます
