### ISSUE TITLE
実績に関する仕様をwikiにまとめる

### ISSUE THREAD

**Issue by ide-an** [android-spa-titech/HQTP#199]
どんな実績があるか、その実績はサーバーの処理のどの辺で行うかをまとめる。

**Comment by ide-an** [comment]
https://github.com/android-spa-titech/HQTP/wiki/achievements にまとめてある

**Comment by draftcode** [comment]
DONE?

**Comment by cloverrose** [comment]
疑問点が出てきたのでReOpenします。

post_inserted実績は自分の投稿にレスをした場合実績はどうしましょうか？
attend_lectureの定義が曖昧なままです

**Comment by pxp-baba** [comment]
こちらでattend lectureについて，そもそも実装するのかどうか結論を出しましょう

もちろん機能としてはあったほうが面白いと思いますが，確かに実装ははっきりしませんね…
「講義に出席」は，「タイムラインにコメントする」と同義でいいと思います
あとはtimedeltaかなんか使えば，「その日のうちに」も実装できそう…?

**Comment by cloverrose** [comment]
@strviola そうですね、こちらで議論詰めてしまいましょう。

解決しないといけないことがいくつかあって、
まずどの授業に参加したかまで考慮するのか？
 `name='attend_lecture,Y12345'` という感じで扱えばいけないこともない？

投稿で出席にする　VS　タイムライン取得で出席にする？
投稿なら、連続投稿と同じで（同じ授業での）前との間隔を見ればいいはず
取得だと、データベース変更するか外部ファイルに吐き出すかして、User_lecture_datetime（もしくはUser*datetime）を保存すればいい？

タイムラインを開いたら出席しました！ってでると面白そうなので取得で出席にしたいな

**Comment by pxp-baba** [comment]
どの授業に出席したかは区別しなくていいと思います。
「1日1回だけ取得できる実績がある」というのが大事なので。
むしろログインすれば「出席」扱いでいいかな、とも考え直したんですが、
ある程度のアクションは確かに必要ですね。
「授業のタイムラインを取得する」なら感覚的にも合っている気がします。

「授業に出席」⇔「何かしらの授業のタイムラインを取得」でいきましょう

**Comment by cloverrose** [comment]
@strviola OK
#263 で実装します
