### ISSUE TITLE
TwitterのユーザーIDと名前を結びつける

### ISSUE THREAD

**Issue by draftcode** [android-spa-titech/HQTP#20]
ユーザーID(番号)と名前を結びつけるようにする。名前はTwitterのユーザー名を使うか、自分で設定できるようにするかを決めないといけない。

**Comment by cloverrose** [comment]
https://docs.djangoproject.com/en/1.4/topics/auth/#storing-additional-information-about-users
を参考にして、branch issue20で実装しました。
@strviola 
レビューお願いします

１つテスト書いたけど、Djangoに込みいった処理をしているので、
いくつかテストを追加してバグチェックをお願いします
