### ISSUE TITLE
コミュニケーション方法についての発表をする

### ISSUE THREAD

**Issue by draftcode** [android-spa-titech/HQTP#21]
5/30の授業でコミュニケーション方法について発表しなければいけないので、その発表準備および発表を行う。

**Comment by cloverrose** [comment]
Dropboxに2012-05-23フォルダ作ってあげておきました。軽くチェックお願いします

**Comment by draftcode** [comment]
早速の作業ありがとうございます。チェックしました。こんな感じで良いと思います。

**Comment by draftcode** [comment]
cloverroseさんがお休みになってしまったので、代わりにnkbswさんが発表してくれることになりました。ありがとうございます。
