### ISSUE TITLE
デザインを何とか見れたものにする

### ISSUE THREAD

**Issue by draftcode** [android-spa-titech/HQTP#217]

**Comment by draftcode** [comment]
なんかデザインが全体的に適用されていないのでReopen。というかデザイン関係は継続して修正するので、このままOpenにしておきましょう。

**Comment by Biacco42** [comment]
風邪で寝込んでましたすいません。
今dropboxの方にいくつかのデザイン方向性でつくったアイコンがimagesフォルダに置いてあります。
確認の上、どのデザインの方向性が好ましいか教えていただければその方向で行こうと思います。
基本はandroid_shadowで行こうと思ってますが。
