### ISSUE TITLE
日付を跨って挟み込もうとすると変な日付でポストされる

### ISSUE THREAD

**Issue by draftcode** [android-spa-titech/HQTP#218]
10/15のポストと、10/31の日付区切りの間に投稿しようとすると、10/23にポストされてしまう。10/15にポストされるのが望ましい。

**Comment by pxp-baba** [comment]
現在の実装では、2つの仮想タイムスタンプを指定すると、
その算術平均を取って投稿するようになっています
「日付をまたぐことまで考えていなかった」というのが本音ですが、
仕様を厳密に決める必要があり、非常に難しい問題です

・この例の場合、具体的には10/15日の何時何分何秒にポストされるべきか?
・場合分けなどを行った場合、仮想タイムスタンプの仕様が満たされなくなることはないか?

**Comment by draftcode** [comment]
いや、これ単純にクライアントの問題でクライアント側が日付区切りの部分の扱いを変えるという感じだと思うんですが。

**Comment by pxp-baba** [comment]
$B%/%i%$%"%s%H$G$7$?$+!"<:Ni$7$^$7$?(B
$B%5!<%P!<$O4X78$J$$$G$9$M(B?

**Comment by ide-an** [comment]
メールで返事返すとiso-2022jpになって文字化け起こすのかしら
