### ISSUE TITLE
実績取得APIの仕様変更（total_pointフィールドの削除）

### ISSUE THREAD

**Issue by ide-an** [android-spa-titech/HQTP#226]
https://github.com/android-spa-titech/HQTP/commit/08f6e79fdedaa4fd3b06c7b5ce4040043f3b2d46#commitcomment-2085536 に関して@cloverrose と@ide-an で議論した結果、実績取得APIのレスポンスにおいてtotal_pointフィールドが不要なのではないかという結論に至りました。
これに関してもう少し議論を詰めたいです。

**Comment by cloverrose** [comment]
### draftcodeさんと話し合った内容をまとめます

#### 結論

total_point必要

#### 理由

サイドバーで表示するtotal_pointを更新するタイミングは実績をPollingでGetした時がほとんど。
更新方法として
1. GET /api/user/achievementが返すtotal_pointをそのまま使用
2. GET /api/user/achievementが返す各実績のpointを加算して計算して使用
3. GET /api/user/が返すtotal_pointをそのまま使用

1の方法ならAPIの直交性には難ありだけど、一番簡単
2の方法ならtotal_pointを削除してもいいのでAPIの直交性が綺麗、でもクライアントサイドがユーザーのtotal_pointを記憶していないといけない。計算めんどくさい
3の方法も2と同様に直交性が綺麗、計算もしなくていい、同じタイミングで必要な値を別途GETしなければならない

で1の方法を選択します
1の方法を選択したほうがクライアントサイドの実装が簡単になるはず
この場合、各実績ごとについてくるpointはToast「講義を追加 +30」を表示する際に利用して、
total_pointはサイドバーの更新に利用

@ide-an どうでしょうか？

**Comment by ide-an** [comment]
サイドバー自身ではAPIによるポーリングをしない感じに聞こえるんだけど、そういう解釈でいいのかな？
それとも実績通知まわりもサイドバーに絡んでくるのか。

**Comment by cloverrose** [comment]
自分は、一番最初はUser情報取得APIでTotalPoint取得して、
それ以降ポーリングしてる実績取得APIからTotalPointを取得して更新でサイドバーにも絡むという理解。

**Comment by ide-an** [comment]
@cloverrose 
ということはサイドバーそれ自身がAPIぶん投げるロジックを抱える必要はない、ということかな。
GUI部品としてはそれが正しいと思うけど各アクティビティに更新ロジックを追加しないといけないとしたらめんどいかなとも思える

**Comment by cloverrose** [comment]
@ide-an 
すでにクライアント側でtotal_pointの更新をサイドバーで行なっている
https://github.com/android-spa-titech/HQTP/commit/d171d6344876f2f1ccca3f771931a8a352ca02c2
ので、どうしようかなーtotal_pointなくしても問題無さそうな気がしてきた。二転三転しててごめん

**Comment by draftcode** [comment]
@cloverrose 
サイドバーではAPI投げて、その結果を表示すると思うんだけど、そのとき表示するのにtotal_point要るという話じゃないの？

**Comment by draftcode** [comment]
なんか混乱してませんか？話があってない気がする。

サイドバーでポーリングして、その結果として返ってくるものをどうしようかという話ですよね。だからポーリングするしないではないです。

1だとサイドバーがポイントを保持している必要はなくて、2だとサイドバー自身がポイントの合計をしなければいけない。3だとToastだすための情報なくて仕様を満たせない。ということになりますね。じゃあサイドバーで状態をsince_id以外持たないようにするために1にして、サイドバー自体の実装はAPIポーリングするなりなんかして、返ってきた結果のtotal_pointをユーザーのポイントとして表示しつつ、新しく来た実績をToastで表示するという実装に落ち着くと思うんですが。

**Comment by draftcode** [comment]
ただ、サイドバーのsince_idはどっかで保存しないといけないですね。あと立てたスレッドの終了って誰がやるんだろうという感じになります。Contextが明示的にstopしないといけない感じ。

**Comment by draftcode** [comment]
Lingrで @cloverrose と確認したことのまとめを書いておきます。

どうやらサイドバーでどこまでやるのかというところで、認識の齟齬があったらしく、自分はサイドバーがgetAchievementsしながらToastだしてtotal_pointを更新するという認識だったんですが、どうやら @ide-an のソースコードを見る限りだとgetUserしてtotal_pointを更新するという感じのようですね。@ide-an の実装だとgetAchievementsにtotal_pointいらないという感じにまとまるのは納得できます。

ただ、どうせgetUserでポーリングするんだったらgetAchievementsでポーリングしてtotal_point取得とToast表示一気にやったほうが良いと思うのですが、どうでしょうか？

**Comment by ide-an** [comment]
実績通知もサイドバーがやる仕事ということか、なら納得。
そうするとgetAchievementsがtotal_pointを返すのが妥当っぽいですね。

スレッドの終了周りに関してはサイドバーのViewがスレッドの開始と終了用のメソッドをそれぞれ持っていて、アクティビティのonStart/onStop時に呼んでもらうという感じで書いてます。

**Comment by ide-an** [comment]
まとめると
- total_pointフィールドは必要
- 実績通知はサイドバーの機能として実現する
- そのためgetAchievements()で取得したtotal_pointをサイドバーでの表示に使用する

といった感じで結論が出た感じなのでこのIssueを閉じます。
