### ISSUE TITLE
CSRFオフのマージタイミングでself.cを利用してるコミットが発生

### ISSUE THREAD

**Issue by cloverrose** [android-spa-titech/HQTP#233]
CSRFオフのマージがタイミング的に

https://github.com/android-spa-titech/HQTP/commit/92b7f337c8f3a9ea43f16e72863d2b6cc0198fa2

のCSRFをオフできないので修正

**Comment by cloverrose** [comment]
一応修正Branchはできてますが、いい解決法があるとアレなのでPushはまだしてません

**Comment by cloverrose** [comment]
testで落ちるだけで運用部分は問題ないのでそこまで深刻ではないけど、

https://github.com/android-spa-titech/HQTP/commit/049dd65b3589163f1fbaf62b99bf9887f6677a25

ではテストが通らないことを覚えておく必要が有る

**Comment by draftcode** [comment]
えっと、差分取得のコードの中にself.cを利用してるコードがあって、それをそのままマージしちゃったってことですかね。だったら、適当に修正してPR投げてください。
