### ISSUE TITLE
パンフレット・Webサイト用に必要な提出物

### ISSUE THREAD

**Issue by cloverrose** [android-spa-titech/HQTP#235]
メールでもお伝えした、パンフレット・Webサイト用に必要な提出物
1. アプリのスクリーンショット1枚
2. ソフトウェアの簡易説明（100字以内）
3. メンバー分のメンバー紹介（名前＋一言メッセージ40字以内）

締め切り１１月１０日

**Comment by cloverrose** [comment]
ソフトウェアの簡易説明（ジャスト100字）考えました

> 質問・回答、画像アップロードなどにポイントを与え、ゲーミフィケーションを通して授業を楽しくするアプリ。授業中のどこへの疑問なのか、どの質問への回答なのかわかりやすい「投稿したい時間」投稿システム採用！

**Comment by ide-an** [comment]
メンバー紹介（ide_an）

```
技術リーダーです。クライアント側の開発を担当しました。Android難しい＞＜
```

こんなところでどうでしょうか・・・

**Comment by cloverrose** [comment]
メンバー紹介(cloverrose)

```
SEPGとしてレビュー・ドキュメント化を見守りました。Django楽しい＞＜
```

うーん、こんな感じ？

**Comment by cloverrose** [comment]
あ、それと今日デザイン会社の人と話し合ったところ

ソフトウェアの簡易説明はもう少し長く（２５０字程度？）
ソフトウェアとは別に開発を振り返ったチーム紹介（１００字程度？）
スクショは２枚

が必要になりそうです。去年までのパンフレット持ってるので、改めてお知らせします。

パネルは
チーム・メンバー紹介＋来場者への質問
ソフトウェア紹介
ToBeプロセス
AsIsプロセス
の計４枚を作ることになりそうです

**Comment by cloverrose** [comment]
ITSPのブログのフロントページに `ITSPパンフレット.PDF` 添付しておきました

**Comment by draftcode** [comment]
こんなかんじでどうでしょう？

```
チームリーダーをやっています。趣味はスキーで、最近はどーもくんがお気に入りです。
```

**Comment by Biacco42** [comment]
メンバー紹介(Biacco)

```
GUIデザインの担当をしました。Androidのデザインは研究すればするほど謎＞＜
```

こんなんでよいでしょうか

**Comment by cloverrose** [comment]
メーリスも回しましたが、変更が発生しました。必要な物は以下の7つです。
締め切りは11/13（火）になりました。
1. チームのロゴ→手ぬぐいドロイドくんでOK
2. チーム名→&3ID♨でOK
3. **チームの説明　150字以内（イメージ縦50*横3）**
4. **アプリのスクリーンショット＋スクリーンショットごとに短いキャプション（各15文字以内）　2セット**
5. **ソフトウェア名**→hqtp? HQTP? 
6. **ソフトウェアの簡易説明　360文字以内（イメージ縦40*横9）**
7. メンバー分のメンバー紹介（名前＋一言メッセージ40字以内） 写真は授業中に取ることに成ると思います。

**Comment by cloverrose** [comment]
ソフトウェアの簡易説明考えました。教授部分の文章が今ひとつ

> １２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０
> HQTPは、質問・回答、画像アップロードなどにポイントを与え、
> ゲーミフィケーションを通して授業を楽しくするチャットアプリです。
> 
> 従来のチャットと違い、授業中のどこへの疑問なのか、どの質問への
> 回答なのかわかりやすい「投稿したい時間」投稿システム採用！
> 
> 教授にとっても時間を指定した質問により内容のあるフィードバックが
> 期待できます。

**Comment by cloverrose** [comment]
スクショ及びデモのために何かしら授業スライドが欲しいです。
初見で楽しめるスライド（著作権フリー？）知ってる人いますか

俺が作ってやる！でも大歓迎です。

追記
HQTPはPDF表示対応してない（はず）なので、PDFから複数PNGに変換するコマンドのメモ
convert file.pdf page-%03d.png

**Comment by cloverrose** [comment]
ソフトウェアの簡易説明まだ字数あるから
1. HQTP(HyperQ**\* Transfer Protocol)
2. 学生と教師との間の革新的なプロトコルです(ｷﾘ
3. みんなの講義ノートが出来上がっていきます
とか入れたい

**Comment by cloverrose** [comment]
Appleの売り文句的な文章も書いてみた。

**HQTP(HyperQxxxTransfer Protocol) ～学生と教師との間の革新的なプロトコル～**

```
１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０
HQTPはチャットのお手軽さでみんなの講義ノートが出来上がっていく魔法のアプリです。
一番下にしか投稿できない従来のチャットと違い、「投稿したい場所」に投稿できます。
例えば、さっきのスライドがよくわからなかったら、遡ってそのスライドの下に質問でき
ます。質問の下に回答できるので誰かの質問に答えるのも簡単です。議論が一箇所にまと
まるので見返しやすいノートが出来上がります。教授にはどこがわからないのかという内
容のあるフィードバックが届きます。

さらに、質問や回答、ノートや黒板の写真の投稿などでポイントが溜まっていき、自分の
活躍が一目でわかり、HQTPで講義ノート作っていくのがどんどん楽しくなります。
```

**Comment by Biacco42** [comment]
Apple風(悪ノリ)

```
１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０
大学生みんなのためのアプリ、できました。

もうノートをひとりでとる必要はありません。ｈｑｔｐ：／／は友達と会話するような気
軽さで、みんなの講義ノートが出来上がっていく魔法のようなアプリです。今までのチャ
ットアプリと異なり、ｈｑｔｐ：／／では自分の投稿をまるでふせんのように好きなとこ
ろに投稿することができます。ちょっと遅れてしまった質問やタイピングの速度を恐れる
必要はもうありません。考えてもよくわからない数式、読みそこねたグラフ、あっという
間に通り過ぎてしまったスライド…それらの下に質問を投稿しましょう。質問の下にも回
答できるので、誰かの質問に答えるのも簡単です。ただ１人でスライドにメモを取るだけ
のノートから、学生だけでなく教授まで参加する、ディスカッション型のノートへ。投稿
することでポイントがたまっていくゲーム要素で、遊び心も忘れずに。

さぁ、刺激的な授業を始めましょう。
```

**Comment by cloverrose** [comment]
さすがですね！
「ふせん」っていい喩え気に入った。
ｈｑｔｐ：／／は半角にしたほうがいい気がしました。

**Comment by Biacco42** [comment]
文字数わかるように心を鬼にして英数字も全角にしてありますｻｰｾﾝ

**Comment by cloverrose** [comment]
そうかなーとは思いました
半角2文字で全角1文字分として扱って大丈夫だとおもいます。

**Comment by pxp-baba** [comment]
遅くなりました
メンバー紹介(strviola)

```
サーバーサイド担当、プログラマの弟子。落ち込んだりもしたけれど、私は元気です。
```

**Comment by nkbsw** [comment]
遅れてすみません。
メンバー紹介(nkbsw)

```
クライアント開発を担当しました。周りの人に助けられつつなんとか頑張りました。
```

**Comment by cloverrose** [comment]
あとはスクショだけです。どの画面をどんなかんじで撮るのがいいのか考えました。
1. timeline
   - 投稿された画像が表示されている
   - 投稿されたテキストが表示されている
   - 投稿ボタンが表示されている
   - toastで実績取得が表示されている
2. login画面
   - endpoint変更が消えている
   - hqtp://twitterがボタンぽくなっている

login画面で1枚分使うと、間延びしてる感じがあるので、
次の画像と合わせて1枚分にしたほうがいいかも
1. 画像投稿画面
   - 画像を選択し終わっている
   - ボタンのGUIが統一されている

**Comment by ide-an** [comment]
DropBoxに画像放り込んでおきました。
が、ブランチごとで差異があるのでどうにか合わせないといけない・・・

**Comment by cloverrose** [comment]
ありがとうございました。ssフォルダ内の３つをとりあえず提出しました

**Comment by cloverrose** [comment]
スクリーンショット完成版としてDropbox Issue235 ss3を提出しました

タイムライン画像
授業一覧画面にログイン画面をくっつけたもの　の計２枚，Webページにはタイムライン画像を掲載します

**Comment by cloverrose** [comment]
すべてのタスクが完了しました

**Comment by cloverrose** [comment]
パンフレットの暫定版を見ると以下の3つが必要でした
1. スクリーンショット説明
   
   `授業タイムライン 投稿ポイントGet!!`
   `授業一覧とログイン画面`
   でいいですか？
2. プロジェクト紹介タイトル
   
   #258 に割り振りました
3. アプリ名
   
   `hqtp://`
   `hqtp:// (Hyper Question Transfer Protocol)`
   のどちらかだと思いますが、どうしますか？

暫定版はDropbox Issue258/2012-11-21 17.59.29_markup.jpg　に置いときました

**Comment by draftcode** [comment]
1. それで良いと思います。
2. 了解しました。
3. //なしのhqtpなのかなと思っていました……

**Comment by cloverrose** [comment]
3 なるほど、 @Biacco42 さんのアプリ紹介文以来自分の中ではhqtp://っておもってました。どうします？

**Comment by draftcode** [comment]
hqtp://でいいと思います。そこら辺決めてなかったですし。

**Comment by cloverrose** [comment]
@draftcode 了解です

**Comment by draftcode** [comment]
パンフレットのデザイン上のバランスで付ける付けないを決めてしまってもいいかも

**Comment by cloverrose** [comment]
://をつける付けない？　(Hyper...)をつける付けない？

**Comment by draftcode** [comment]
://を付ける付けないです。

**Comment by cloverrose** [comment]
じゃあ、デザイナーさんには `hqtp://` です、って伝えてデザイン上 `://` が不自然だったら気軽に `hqtp` にして大丈夫ですという形で伝えます

**Comment by draftcode** [comment]
お願いします。
