### ISSUE TITLE
日付区切りセルのVirtual_tsが12時間ずれてる時がある

### ISSUE THREAD

**Issue by ide-an** [android-spa-titech/HQTP#254]
日付区切りセルの生成の際に

```
cal.set(Calendar.HOUR 0);
```

として0時の時間を生成しようとしているが、この時間はAM/PMの影響を受けるため場合によって12時間ずれると考えられる。
代わりに

```
cal.set(Calendar.HOUR_OF_DAY, 0);
```

とすべき。
同様の問題は日にちが開いた投稿の間に新たな投稿を挟む場合にも生じると思われる。

**Comment by draftcode** [comment]
Oh...
