### ISSUE TITLE
チームの説明　150字以内（イメージ縦50*横3）

### ISSUE THREAD

**Issue by cloverrose** [android-spa-titech/HQTP#258]
リーダーお願いします
#235 のサブタスク

**Comment by draftcode** [comment]
了解です。

**Comment by Biacco42** [comment]
スクショ等でデザイン上なにかあったら連絡お願いします。

**Comment by draftcode** [comment]
チーム「&3id♨」では「自分たちが使いたいと思うものを作る」というコンセプトに基づき制作を行いました。
開発の過程では、テストやコードレビューのようなベストプラクティスを実践しつつ、最初は小さな要件から
始まり、だんだんと要件を追加していく、段階的な開発プロセスを実践しました。

**Comment by draftcode** [comment]
Closed?

**Comment by cloverrose** [comment]
Dropbox Issue258/2012-11-21 17.59.29_markup.jpgにパンフレット暫定版おいておきました。
このプロジェクト紹介タイトルが必要になりました。

いくつか案出しておきました。
ベストプラクティスの実践結果はいかに!?
開発コードネームはAtami, Beppu, Chichibu！
温泉？まだ行ってないぜ！

**Comment by draftcode** [comment]
なんかテンション高い紹介タイトルのほうが良い感じですか？

**Comment by draftcode** [comment]
「ベストプラクティスの実践結果はいかに!?」とか割と気に入っているんですが、実践結果を比較検討できるデータがあるわけではないので「ソフトウェア開発におけるベストプラクティスを実践」みたいな無難なタイトルになってしまう。

**Comment by cloverrose** [comment]
パンフレットのチーム紹介を読む導入役を狙っているのでキャッチーに越したことはないかなと思ってテンション高くしました。

**Comment by cloverrose** [comment]
ベストプラクティスを武器に闘い抜いたチーム開発
とかどうですか？

**Comment by draftcode** [comment]
「実践！ベストプラクティス」とか？

**Comment by cloverrose** [comment]
OK，「実践！ベストプラクティス」で行きましょう
