### ISSUE TITLE
Pull Requestの仕方についてWikiに書く

### ISSUE THREAD

**Issue by draftcode** [android-spa-titech/HQTP#26]

**Comment by draftcode** [comment]
@nkbsw 

Pull Requestについて書いたので、GitHub for Macの項目とあわせてレビューしてください。

https://github.com/android-spa-titech/HQTP/wiki/GitHubForMac
https://github.com/android-spa-titech/HQTP/wiki/HowToSendPullRequest

レビューというか、変なよくわからないところとか、間違っているところ、誤字脱字があるかどうかみたいなチェックですね。そういう点があればここでコメントしたり、直接Wikiの方を編集してください。OKだったらOKとコメントを。よろしくお願いします。

**Comment by nkbsw** [comment]
実際にやったわけではないので完全にとは言えないですが、一通り理解できたのでOKだと思います。

**Comment by draftcode** [comment]
ありがとうございます。ではこれでCloseしますね。
