### ISSUE TITLE
実績 "Consecutive Post" の実装

### ISSUE THREAD

**Issue by pxp-baba** [android-spa-titech/HQTP#260]
直前の投稿(投稿者は問わない)から5分以内に投稿を行った場合，
その投稿をした者に実績 `consecutive_post` を与える．

**Comment by cloverrose** [comment]
確かにWikiだと「投稿者は問わない」と読めますね
僕と@ide-an は「同じ人の連続投稿」と認識していました。

**Comment by pxp-baba** [comment]
書いておいてよかった…
実装は「投稿者を問わない」ほうが簡単ですが、ゲームとしてはどうでしょうかね?

**Comment by cloverrose** [comment]
実装はどちらも同じ複雑さだと思う。

```
def latest_post_time(user_obj):
    return user_obj.post_set.aggregate(Max('posted_at'))['posted_at__max']
```

**Comment by cloverrose** [comment]
その上でどちらがいいか考えても、結論はでないんだよねー
クライアントで現在は「またお前か」って出すようにしてる。
それが「ksk」「ｋｓｋｓｔ」とかになるって感じだよね。

明日決めよう
