### ISSUE TITLE
ユニットテストのget関数の改良

### ISSUE THREAD

**Issue by pxp-baba** [android-spa-titech/HQTP#262]
現在、ユニットテストにおいてデータベースから実績データを直接取得する関数 `get_achievements_from_db` はリストを返している
これをディクショナリを返すように変更し、この関数を用いている部分も修正する

**Comment by cloverrose** [comment]
@strviola 実装してしまってからだと申し訳ないので取り急ぎ

これはリストのままのほうがいいと思います。
現在は実績が何もない初期状態から何かアクションを起こして、どんな実績がもらえたかを確認していますが、
一般的には実績をすでに持っている初期状態からテストをしたり、
ユニットテストではやらないテストかも知れませんが、
一連のシーケンス（認証→投稿→レスされるなど）をテストした場合に、実績がもらえた順序が保存されていたほうがいいと思います。

時期的にリファクタリングは本当に必要でない限り、他の人がコミットしにくくなったり、コードレビューの負担がますので控えていきたいと思っていますが、どうでしょうか

**Comment by pxp-baba** [comment]
なるほど、順序は確かに大事ですね
貴重な意見、ありがとうございます
