### ISSUE TITLE
実績"Attend Lecture"の追加

### ISSUE THREAD

**Issue by cloverrose** [android-spa-titech/HQTP#263]
attend_lectureは
0:00~23:59の間に任意の授業のタイムラインを取得すると取得できる

同じ日に複数回実績を取得しないように注意する

attend_lecture実績の内最近のものの日付と異なる日付で取得を行なっていたら実績を付与する

**Comment by ide-an** [comment]
実績の日付の区別は`created_at`を見て行うという認識でいいでしょうか。
実績の`name`が変わる場合クライアント側のコードも数行いじることになるのでその辺確認しときたいです。

**Comment by cloverrose** [comment]
@ide-an 
そのとおりです．created_atを見ます，nameは変わりません
クライアントとのAPIには影響でません
