### ISSUE TITLE
サイドバーのユーザーアイコン用に少し大きい画像（を｜も）用意する

### ISSUE THREAD

**Issue by cloverrose** [android-spa-titech/HQTP#268]
現在のGUIでサイドバーのユーザーアイコンがぼやけています

Twitterで取得できる画像の中でandroid_onsen_normal.pngで取得できる画像を提供しています。
android_onsen_bigger.pngとTwitterに要求するURLを変更すれば少し大きい画像が取得できます。

方針として
1. icon_url_biggerを新たに用意して２つの画像をHQTPサーバーに保存する
2. 保存する画像をnormalのものからbiggerのものに変更する

の２つあります、クライアントサイドでbiggerの画像を使ってもTimelineユーザーアイコンがうまくいくなら２つ目の方法でいきたいと思います。

**Comment by cloverrose** [comment]
DropboxのIssue268に参考画像上げておきました

**Comment by cloverrose** [comment]
複数の画像を用意する方針は実装の負担なので止めます。

Twitterから取得する画像のURLをusericon_normal.pngからusericon_bigger.pngやusericon.pngにすることで
問題を解決しようとしてます。

Pushされてるコードではまだ何も変更してません。uWSGIで動かしてるコードではスクリーンショットを取るために
オリジナルサイズの画像(usericon.png)を使っています。

12/5に下見に行った時に大きい画像だと通信圧迫するか確認して見ようと思っています。

**Comment by ide-an** [comment]
今実機で見た時にアイコンの解像度が高いのはコードを変えてるからではなくサーバーに置いてる画像を置き換えているからということですね。
了解です。
