### ISSUE TITLE
Git + Eclipseの組み合わせでの使い方についてドキュメントを書く

### ISSUE THREAD

**Issue by ide-an** [android-spa-titech/HQTP#27]
おそらくEGitを使えばいいと思います。

インストール/設定まわりの話とコード編集→コミットの流れについて書けばとりあえず足りるかと

**Comment by draftcode** [comment]
EGit使いますか? なんか今日の話では使わなさそうという感じになりましたが。

**Comment by ide-an** [comment]
EGitのいい噂が聞こえないし、pull→commit→pushという流れをやる分にはGitHub for Macあたりでやってしまってもよさそうですね。

**Comment by draftcode** [comment]
OKじゃあ、やらないということでCloseしますね。
