### ISSUE TITLE
投稿入力時に投稿ボタンがキーボードで隠れる問題について

### ISSUE THREAD

**Issue by ide-an** [android-spa-titech/HQTP#272]
投稿画面において投稿内容を入力する際にキーボードが表示されるが、これによって投稿ボタンが隠れてしまう。
そのため投稿ボタンを押すために一度キーボードをしまう(↓ボタンを押す)必要がある。
対策としてキーボードが表示される際に投稿ボタンを移動させて隠れないようにしたい。

このIssueではとりあえず技術的にできそうか・実装の難易度が高いかどうかをコメントに書いてもらいます。
実際に実装するかどうかはその後に決めることにします。

このIssueはそんなに優先度は高くないので無理そうなら投げてもOKです。

**Comment by cloverrose** [comment]
授業追加時の問題も

**Comment by ide-an** [comment]
追加時の問題とは。

授業追加のときにキーボードで「追加ボタン」が隠れるのは別に問題じゃないと思っている。
というのも授業追加は投稿と比べて頻度が少ないし、追加の操作に少しくらい手間があっても問題ない(むしろ誤操作で追加されるのを防ぎたい)と思っているので。

**Comment by cloverrose** [comment]
これを書いた経緯として，
現在「バックボタン」があるべきところに「キーボード隠すボタン」が表示されていて
前の画面に戻るときに，「キーボード隠すボタン」→「バックボタン」と2回押さないといけない．

「追加ボタン」が隠れなければ，「キーボード隠すボタン」の位置に「バックボタン」が表示されるのかなと思って，
実際やってみると，キーボード隠すボタンが表示されていました．

**Comment by ide-an** [comment]
@cloverrose 
Androidデフォルトの操作体系を覆すことはしたくない。
講義追加画面に関してはこのIssueの対象外にしたいです。

**Comment by cloverrose** [comment]
Androidのデフォルトをいじることは考えていなくて，
Androidが賢くて，GUI部品が何も隠されていなければ，自動でバックボタンになるのかと思ってた．

Dropbox Issue272にボタンを表示させたスクショ上げておきました．
縦向きだと，ボトムバーも表示されてしまうのはもう少し工夫しないといけない．

追加ボタンを表示させても，2回ボタンを押さないといけないことには変わりなかったので，
講義追加画面はIssueから外して問題無いです
