### ISSUE TITLE
内部発表準備

### ISSUE THREAD

**Issue by cloverrose** [android-spa-titech/HQTP#274]
11/ 28 発表20分、質疑10分

六本木では各チームにディスプレイ使えるので、
ここでの準備は六本木でも役立ちます。
まずはどのような発表にするか決めましょう

基本的に商品売り込みスタイルなので、おしゃれなスライドは欲しいです。
デモで何するかも決めないといけません。
デモで実機を配るか否かも決める
プロモーションビデオを作った年もあるようです、 ref. #10 Path

**Comment by cloverrose** [comment]
Dropbox Issue274にスライド・プロモに良さげなイメージをパワポで作ってみました

**Comment by cloverrose** [comment]
動画で簡単でそこそこおもしろいので24Effectなどがあったなあ

**Comment by cloverrose** [comment]
#109 で時間配分などを参考にでできる

**Comment by draftcode** [comment]
InternalAnnouncement.pptxのレビューです

全体的にこんな感じの方向で良いと思います。これが売りですというのがよく強調されていると思います。あとは、そのアプリケーションがどんな動きをするのかについて、ざっくり説明できる静的なスライドを、デモとは別に用意するといいかなとおもいます。

例えば、 [Basecamp](http://basecamp.com/one-page-project) というサービスでは、我々の製品はこんなことができる、というのを実際の画面の上に乗せて説明しています。こうすると、使い方が事前にスライドでわかる+そのあとのデモで何をやっているかが把握しやすいのではないかなと思います。

我々がやるのであれば、例えば、ログイン画面のここを押すと、Twitterに飛んで、戻ってきて、授業一覧が出てきて、授業一覧の授業をクリックすると、こんなタイムラインの画面が出てきます、という流れを「ログイン」「授業一覧」「タイムライン」の3画面をスライドに乗せて説明するとかがよいのではないでしょうか。

**Comment by draftcode** [comment]
あ、あとよくわからないですが、チーム紹介以降、今回の発表で要るのだろうか？どっちなのかよくわからないです。

**Comment by cloverrose** [comment]
つまり背景・要求、提案、hqtp://紹介、デモだけでいいという感じ？
日本語的にチーム紹介がどっちかわからない

**Comment by draftcode** [comment]
背景・要求、提案、hqtp://紹介、デモだけでいいという感じがしていました。

**Comment by cloverrose** [comment]
了解です。レビューありがとうございました。

**Comment by draftcode** [comment]
発表までcloverroseさんやります？

**Comment by cloverrose** [comment]
無理だす

**Comment by ide-an** [comment]
デモでやることとしては大雑把に
- ログイン (Twitterでの認証を含むケース、2回目以降のログインを示す必要はないと思う)
- 講義一覧→タイムラインへの遷移
- 投稿(テキストのみ。URLを含む投稿だと実績も見せれていいかも)
- 画像投稿(カメラとギャラリー)
- 授業追加

といったところですね。
それぞれについてどんなシナリオで見せましょうか。。。

**Comment by draftcode** [comment]
一つのシナリオで出来る範囲に限定してみましょうか。ストーリ仕立てにすると

こんなかんじでログインできます→こんなかんじで講義一覧が出るので、この授業を選択します→こんなかんじでタイムラインがあるので、ここに挟んでみましょう→投稿してみます→投稿できました→次はここに撮った写真を投稿しましょう→こんなかんじで投稿されます

という感じでしょうか。授業追加はまぁやらなくてもいいかなぁ。

**Comment by cloverrose** [comment]
スライド 2012-11-28_onsen.ppt 完成しました。
@Biacco42 ご指導お願いします

**Comment by cloverrose** [comment]
レビューを反映して　「好きなところに投稿できる」ページを抽象的な付箋から実機キャプチャに修正
