### ISSUE TITLE
授業一覧画面の自動更新

### ISSUE THREAD

**Issue by cloverrose** [android-spa-titech/HQTP#285]
他と一貫性がないので更新ボタンを削除して，ポーリングにする

**Comment by ide-an** [comment]
授業の追加が行われる頻度って小さいと思うので頻繁なポーリングを行うことにはあまり意味がないのではないかと思う。
代わりに他の画面から講義一覧画面に遷移してきたとき(onStartないしonResume)に更新をかければ十分なのではないかと思っている。
これであれば講義追加操作から戻ってきた時に一覧が更新されるので、自分が講義追加操作したときに更新操作を行う手間が省けるようになる。
ということで『「更新ボタン」を残す + onStartまたはonResumeで更新する』といった感じでいいと思う。

**Comment by cloverrose** [comment]
『「更新ボタン」を残す + onStartまたはonResumeで更新する』で了解です．

デザインをFixしないとスクショが撮れないので，議論出しました．
更新ボタン消したいのは完全にデザイン重視な案ですので
