### ISSUE TITLE
サーバーとの通信を実装する

### ISSUE THREAD

**Issue by ide-an** [android-spa-titech/HQTP#31]
通信はHTTPで行う。
Cookieが使えるようにしたい。
HQTPProxyクラス中に実装すればいいと思います。

**Comment by draftcode** [comment]
テストを書いてみてますが、authenticateあたりがどういう流れになっているのかよくわからないですね。

Singletonなので、どこかのタイミングでsetAccessTokenしたあとにauthenticateを呼び出す形ですか? それだったらauthenticateの引数でaccessTokenを指定してあげてもよい気がします。

また、revokeAuthenticationという感じのメソッドを追加したりとか、投稿や取得ができなかったときに例外を投げるようにするとかが必要かも。

**Comment by ide-an** [comment]
authenticateとsetAccessTokenを分けたことに深い意味はないのでaccessTokenをauthenticateの引数にしてもいいと思います。

revokeに関してはサーバー側のAPIの追加も必要になると思うので、そっちの仕様を考えた上で追加しようと思います。

いくつかのメソッドで戻り値をboolにしてますが、この辺は投稿などが成功したかどうかを返すということで考えていました。
ですが、投稿失敗の理由も複数考えられる(認証してない、フォーマットに合わないなど)ことを考えると例外を投げるほうが適切だと思います。
