### ISSUE TITLE
クライアント側のテストプロジェクトの作成

### ISSUE THREAD

**Issue by ide-an** [android-spa-titech/HQTP#32]
クライアント側のテストが書ける環境を構築して欲しいです。
http://www.atmarkit.co.jp/fsmart/index/androidtest.html
この辺が参考になるかと思います。

**Comment by draftcode** [comment]
了解です。ちょっとまってね。

**Comment by draftcode** [comment]
環境構築のみで大丈夫ですか? というのも、こちらのissueを早めにマージしてしまったほうが、 #31 が実装しやすいかなと思って。

あと、DIフレームワークとか、JVMを利用したAndroidのテストフレームワークとか、Mockingフレームワークを使ってます。それなりにまともなテスト環境だと思うのですが、使い慣れてない人も多い(というか自分もMockしか使ったことがないし、DIが必要ないLLな言語しか使ったことがない)と思うので、なんでそんなの使うのかとか、そこら辺の説明もWikiにあげておいたほうが良さそうですかね。

**Comment by ide-an** [comment]
このissueについては環境構築のみでOKだと考えています。早めにマージしてOKです。
いずれにせよ#31のブランチをマージするのは面倒臭そうな気がするけど、多分#32を先にマージした方が楽だと思います。
