### ISSUE TITLE
認証方法についての再考が必要

### ISSUE THREAD

**Issue by draftcode** [android-spa-titech/HQTP#33]
以前AccessTokenもらっちゃうのどうなんだろうねという話をしたときに、自分が「AccessTokenとそれを使用するアプリって結びついているはずだから、User側からRevokeできるし、それを使い回して良いんじゃない」的なことを言った気がしますが、AccessTokenとそれを使用するアプリは結びついていなかったようです。ごめんなさい。

参照: [単なる OAuth 2.0 を認証に使うと、車が通れるほどのどでかいセキュリティー・ホールができる](http://www.sakimura.org/2012/02/1487/) (概要としては、攻撃者が適当なアプリを作って収集したAccessTokenを利用して、我々のアプリケーションから情報を引き出すことができるというものです。本来、情報を渡してはいけない人に情報を渡してしまうという点でセキュリティーホールです。)

ということで、AccessTokenによる認証は微妙……ということになります。で、先にあげた記事ではAccessTokenを取得するのに、もう一段階やりとりが必要になる感じのOpenID Connectを押してるみたいですね。が、Twitterはそれに対応していないようです。

なので、しばらくは考えなくても良いと思うのですが(たぶんそこまで大規模な修正が必要なモノでもないので)、そのうち何らかの対策をしたほうがよいのではという問題であります。

**Comment by cloverrose** [comment]
#76 をみて思ったんですが、
Twitter以外にFacebookなどの認証を考えると
違うSNSで同じIDが使われている可能性があるので、
HQTPで管理する一意のユーザーIDをどうするかという問題が発生します。
（現在はTwitterのIDを使用してます）

その他次のものをユーザー情報として管理しないといけないでしょう
　SNSの種類（Twitter,Facebook etc..）
　SNS内の一意のID
　SNS内での名前（Twitterならscreen_nameとname）

**Comment by cloverrose** [comment]
@ide-an さんと軽く話し合った結果、
サーバーで一意に割り当てたユーザーIDは必ず返す
表示用のユーザー名はatamiではTwitterのひらがな使える名前を返す

**Comment by draftcode** [comment]
@cloverrose 

表示用のユーザー名は、ユーザー登録時に取ってきた名前を使い続けるという仕様にしますか? 質問の一覧を要求されたときに、毎回取得するのは現実的ではなさそうですが。

**Comment by cloverrose** [comment]
@draftcode 
そうですね
Twitterのユーザー名を頻繁に変える人（ほげほげ＠うんチャラかんちゃら中　的な人）もいますが
最初は考えなくていいですね。

ラグを許すなら、定期的にTwitterにアクセスして名前を更新ってかんじですかね

**Comment by draftcode** [comment]
@cloverrose 
もしくは、最初のユーザー登録時に初期値としてTwitterの名前を取ってきて、それ以降はユーザーに名前を変更する操作を許可しても良いと思います。いずれにしても、最初には考えなくても良いことは確かですね。
