### ISSUE TITLE
server-side　GET、POSTの返り値テストの作成

### ISSUE THREAD

**Issue by cloverrose** [android-spa-titech/HQTP#39]
サーバー動作の確認を自動でテストできるようにテストケースを記述

**Comment by draftcode** [comment]
自分もDjangoのテストについて調べてみますね。

**Comment by cloverrose** [comment]
https://docs.djangoproject.com/en/1.3//topics/testing/#module-django.test.client
を参考に、クライアントのテストケースを記述しました。
Djangoのテストの詳細については後でWikiに書きますが、python manage.py testでテストが走ります。
/api/post/についてはCSRF対策を有効にしているのと無効にしているものの両方を書いておきました。
試しに、@csrf_exemptを削除して同じように実行するとエラーになることが解ると思います。
