### ISSUE TITLE
投稿画面を作る

### ISSUE THREAD

**Issue by ide-an** [android-spa-titech/HQTP#40]
投稿画面のアクティビティを作成し、UIを設計し、機能を実装する。
機能に関しては
1. RoboAsyncTaskクラスを継承したクラスを作る
2.↑のクラスの中でHQTPProxyのpostQuestion()を呼ぶ
3. 1.のクラスを生成して実行するコードをUIのイベントハンドラに仕込む

といった手順でやればOKです。
UIデザインについては任せます。

**Comment by hiroqn** [comment]
とりあえずのUIでつくりました

**Comment by draftcode** [comment]
@hiroqn 

ちょっとコードを修正したのと、PostQuestionActivityのテストを追加しました。良さそうだったらPull Request送ってね。
