### ISSUE TITLE
サーバーサイドの認証について

### ISSUE THREAD

**Issue by cloverrose** [android-spa-titech/HQTP#41]
とりあえず作って、認証周りの議論のたたき台になればと思ったので、サーバーサイドでデータベース（仮）を定義し、
get,postに対してload,saveを行うようにし、
こっちは怪しいんですが、authに対して未登録ユーザーの場合に新規作成という動作にしました。

それと認証の流れをtest.pyに書きました。

クライアントで実装するのと、Django組み込みのテストクライアントで処理するのとでは
違いがあって、僕の勘違いな点もあるかと思うのですが、意見として

１．認証に際して、ユーザーのパスワードはアクセストークンを引数として渡すが
名前をどう渡すかがはっきりしていない？

２．クライアント側は、最初の認証でサーバー側にユーザー作成の依頼（authの呼び出し）をして、
その後ログインして発行されるcookie,sessionを保存すればいい？
OR サーバーはauthで作成とloginの両方を行う。（どちらにせよ内部では２つの処理が行われています。）

**Comment by ide-an** [comment]
1.に関してはtwitterのAPI(GET account/verify_credentials)でtwitter上でのユーザー名などを取得できるようなので、それを使えばいいと思います。
http://stackoverflow.com/questions/6131845/getting-twitter-username-with-access-token
https://dev.twitter.com/docs/api/1/get/account/verify_credentials

**Comment by cloverrose** [comment]
１．TwitterAPIをTweePy叩いてユーザーID、ユーザーネームを取得するように、 #45 で実装。
依然パスワードをどうするかなどの問題は残る

２． api/authを呼び出すだけで、ログインが完了するように、 #43 で実装
