### ISSUE TITLE
クライアントとサーバーの環境構築の仕方について書く

### ISSUE THREAD

**Issue by draftcode** [android-spa-titech/HQTP#44]
チームの開発に入るときに、どういう設定が必要なのかをまとめておきます。チームに新しく人が入るということはないかもしれませんが、違う環境に移ったときに利用できます。また、まだすべての人が環境構築できているわけではないので。

**Comment by hiroqn** [comment]
eclipseのcode styleが統一できてないように思われます。
設定をexportとして共有したほうがいいとおもいます。
手でインデントするのもありますが・・・

**Comment by draftcode** [comment]
@hiroqn 
あー、ちょっと揃っていないところがありますね。ありがとうございます。まぁ、コーディング規約というのはあったほうがよいけど、という感じなのかなと思っています。こだわりすぎてもアレだし。

@ide-an 
ということで、EclipseのFormatterの設定作れますか? と言っても、Tab→SpaceとInjectみたいなタグがぶら下がるかどうかぐらいかと思いますが。

@cloverrose 
サーバーサイドのほうはどんな感じにしましょうか? 別段、エディタがまちまちなのでどうしようかという感じなんですが。こう、というものがあるのであれば少しまとめることはできますか?

**Comment by draftcode** [comment]
これは今のWikiに書いてある感じで大丈夫ですかね……
