### ISSUE TITLE
AccessTokenからTwitter情報を取得

### ISSUE THREAD

**Issue by cloverrose** [android-spa-titech/HQTP#45]
Tweepyを使いサーバーサイドでAccessTokenにひもづけられている情報を取得

**Comment by cloverrose** [comment]
https://dev.twitter.com/docs/api/1/get/account/verify_credentials
の方法でTwitterのid,screen_name,nameを取得するにはアクセストークンKEY,SECRETの両方必要です。
よって、api/auth/?access_token_key={KEY}&access_token_seceret={SECRET}
といったように両方渡せる形式に変更する必要があるかと思います。

**Comment by pxp-baba** [comment]
コード大体見ました。
・consumer_infoはまだ作っていないということでよろしい?
・views.pyのauth_viewが拾う例外を明示した方がいいと思う(大変でなければ)
・コーディングスタイルについて、 = の前後と , の直後に半角スペースを入れたい
・False, Trueは先頭大文字で大丈夫なのか
まだAPIやdjangoフレームワークについて分からない点が多々あるので、これから勉強していこうと思います。

**Comment by cloverrose** [comment]
レビューありがとうございます。
consumer_info.pyはhttps://github.com/android-spa-titech/HQTP/pull/46
に書いたように、Dropboxにあげておきました。
.gitignoreの設定で、githubに乗っからないようにしています。（セキュリティのため）

コーディングスタイルは今ちょうど議論になってました。  #47 
pep8に従う感じにしましょうか？
コミットする前に何かしらチェックをかけてコーディングスタイルが正しくならないとコミットできないように出来れば一番いいですね。

あと最後のFalse,TrueはPythonはこれであってる。JSONオブジェクトにすると違うけどね
