### ISSUE TITLE
Pythonのコーディングスタイル

### ISSUE THREAD

**Issue by cloverrose** [android-spa-titech/HQTP#47]
エディタを統一しないので、コーディング規約の徹底は、コミット前にチェックを自動的にかけるのがよさそう。
pep8 filename.pyでエラーがなくならないとステージング出来ないようにできないかな？→できた

**Comment by cloverrose** [comment]
http://git-scm.com/book/en/Customizing-Git-Git-Hooks
http://bkonkle.github.com/docs/snippets.html#pre-commit-pep-8-checking
を参考に、各自のローカルの.git/hocks/pre-commitを設定してもらうのが妥当でしょうか？

pep8はpipでインストールできるようです。（自分はapt-getで入れたので本当かどうか）

gitのバージョンによってすでにpre-commitがある（自分の環境ではpre-commit.sampleがある）場合は、
競合が発生しないように注意してください。

あと、pre-commitにchmod 775 pre-commitで実行可能にしてください。

pep8以外でこっちのほうがいいっていうコーディングスタイルチェッカーがあったら、教えてください。

**Comment by cloverrose** [comment]
１．現在のサーバーサイドのブランチがmasterにマージされたら、今まで書いたコードのコーディングスタイルを修正する。

２．長い行はhttp://coreblog.org/ats/writing-smart-python-code
を参考にPEP8で指摘してくれないけど、見難いソースを修正

**Comment by cloverrose** [comment]
pep8,pyflakesでの自動チェックをするスクリプトを
http://gist.github.com/ee52cd5a1f1749d1d427
にあげておきました。各自ダウンロードして使ってください。(拡張子.pyは消してね)

**Comment by pxp-baba** [comment]
PEP8について読みました。以降これにできる限り従う形でいいですかね。
あと、そこでも指摘されていましたが、例外を裸で補足するのはやはりやめたほうがいいかと。

もう一つ、動作や定義についてのコメントがもう少し欲しいなと思いました。
ドキュメント化も意識してくれるとありがたいです。

**Comment by cloverrose** [comment]
＞PEP8
自動チェック環境を整えたました。
https://github.com/android-spa-titech/HQTP/wiki/ServerSideDevelopmentEnvironment
↑のコーディングスタイルのところを参照してみて。

＞例外の裸補足
指摘ありがとう。直しておいたよ

＞コメント
少なくてすみません
どこらへんがわかりにくかったか今度教えてください

**Comment by cloverrose** [comment]
issue47-server　ブランチで修正完了、

@strviola  
・pep8,pyflakesのインストール
・pre-commitを配置
して、適当に試してみたら教えて。そしたらcloseします

**Comment by pxp-baba** [comment]
ソースコード、だいぶ読みやすくなりました。
ただ、シェルの流れを書いた複数行コメント? が何をしているのか、
もう少しまとめたコメントがあるとより良いかと

**Comment by draftcode** [comment]
このチケットに関しては、コーディングスタイルのみで終わらせておいて、コメントやドキュメントの整備については、また別に整備することにしましょう。

@strviola 
pep8やpyflakes、pre-commitの設置できました?

**Comment by draftcode** [comment]
ちなみにドキュメントという点では、[PEP257](http://www.python.jp/doc/contrib/peps/pep-0257.txt)もありますが、僕は[Google Python スタイルガイド — PyGuide - 2.29](http://works.surgo.jp/translation/pyguide.html#doc-strings)のdocstringが好きですね;)

**Comment by pxp-baba** [comment]
完了しています、動作確認もしたので大丈夫です
