### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by hiroqn** [android-spa-titech/HQTP#76]
Activities=[PostQuestion,ListQuestion,Login]
each Activities
　each 'UI', 'UX', 'Design'
　　definePresent
　　discusFuture
　　setGoal
if need
　Activities.add

**Comment by draftcode** [comment]
@hiroqn @Biacco42 

えっと、UX担当の人にお願いしたいのですが、アプリケーションの見た目(UI)のデザインだけでなく、ユーザー体験 (UX)までデザインして欲しいのです。つまり、このアプリケーションが、ユーザーの生活にどのように組み込まれていくのかというストーリーを設計して欲しいです。もっと単純な言葉で言うと、ユースケースです。

たとえば、HQTPのターゲットとなるユーザーには大学生が含まれます。この大学生がHQTPを使い始める状況はどのような場合でしょうか。具体的に考えてみましょう。

例えばTwitterやFacebookのタイムラインで誰かがHQTPを使っていたから、とかそういう状況が考えられます。このときに、その大学生がHQTPを初めてダウンロードして使う状況だとしましょう。ここで、HQTPの起動時のロゴが表示されます。このロゴが表示されるのは、何秒以内であるべきでしょうか? UX的には何秒以内が妥当でしょうか? プログレスバーを出したとしたら、どれぐらいその秒数が伸び縮みするでしょうか?

ロゴが表示され終わって、ログイン画面に遷移します。ログイン画面では、Facebookでログインする、Twitterでログインするの二つのボタンがあります。この二つのボタンの位置関係はどうなっているべきでしょうか? この後のユーザーの動きを考えます。そのユーザーのタイムラインで誰かがHQTPを使っているとしたら、その友人とつながっていくというプロセスが含まれるはずです。さらに、HQTPは大学の授業とつながっていくアプリケーションですから、大学や学部・学科の選択が含まれるでしょう。このときに、Facebookのほうがユーザー情報が細かいので、よりそのユーザーに適切な選択肢が提示できそうです。さらに、Facebookのほうが、同じ大学同じ学科のユーザーをリコメンドするということもできると考えられます。こういった理由から、HQTPはFacebookでログインすることを推奨した方が良いと考えられます。(また、セキュリティ上の理由からもFacebookのほうが良さそうなのですが。)このときに、ユーザー全体の右利き、左利きの比率から言って、ユーザーが端末を持つ手はどちらがどれぐらいの割合で、右手で持った場合と左手で持った場合で、右と左、どちら側にFacebookのボタンをおいた方が効果的でしょうか?

このように、ユーザーがどのようなグループに属している人間で、どのようなシチュエーションで利用するのかを考えると、UIに対して理由付けをすることができるはずです。それを行うために、我々がつくるアプリケーションが、どういった利用のされ方をすることを想定しているのかを提示して欲しいのです。そして、その想定に従って、UIがどうあるべきなのかを決定して欲しいです。
