### ISSUE TITLE
夏休みに作業を進める

### ISSUE THREAD

**Issue by draftcode** [android-spa-titech/HQTP#86]
今まで、「夏休みはなんだかんだいって作業が進まないから、あんまり勘定に入れないでおこう」という立場で話をしていたのですが、もしかしたらもう少しコミュニケーションツールを利用したり、適切に管理することで、「夏休みにも作業を進める」というリスクを取ることができるのではないかと思ってきました。

今のところあまり考えてないのですが、夏休み前に要求を固めておいて、チケットを発行して、いくつか割り当てて夏休み突入という感じを考えています。その中で、前回出た「いま作業できる人で集まって作業する」ということができればいいですね。最初の方の話し合いで、チャットとかSkypeとかあまり立ち上げないので利用しないという方針になりましたが、もう一度利用を検討してみるのも良いかなと思います。どうでしょうか。

「夏休みにある程度は作業しなければいけない」ではなくて、「夏休みにちょっと作業が進められればいいかなぁ」ぐらいのスタンスで検討したいです。そこで、もし、夏休みに作業するのであれば、こういう準備が必要で、こういう仕組みがあるとうまくいくのでは、という案を募集します。

その上で、うーんちょっと難しそうだね、ということであれば、夏休みあけてからがんばるということにしてもいいですし。できるのであれば、それはそれでハッピーですね。

**Comment by draftcode** [comment]
ちなみに、「夏休みに作業をすすめる」がなぜリスクなのかというと、進められなかったときに次のような影響がでるからです:
- 進むはずだった作業が進んでないので、工期が遅れる。
- 後期の予定がわからないのに、そちらの方に作業が先延ばしにされる。
- 自分たちが進んでいないという停滞感からくる、チームの士気の低下。さらにそのループ。
- 自分は作業しているのに、他の人は作業していないという不公平感。
- 他の人は作業しているのに、自分は作業していないという背徳感。

特に、チームの士気を下げてしまう最後の3つは一番避けたいところです。常に、「自分たちがいいチームで働いている」という感覚になれないのであれば、夏休みに作業をいれるのはやめておきたいです。

**Comment by cloverrose** [comment]
夏休みに作業をしないリスクとしてせっかく慣れてきたAndroid・Django開発を忘れてしまうというのがありそう

**Comment by draftcode** [comment]
とりあえず2週間に一度ぐらい、集まるorチャットルームで集まれれば、ということで、チャットルームを作ってみました。

http://lingr.com/signup?letmein=android_spa_titech

permitという合い言葉を入れないといけないのですが、androidspatitechに設定しています。

**Comment by draftcode** [comment]
7/31のあつまりでこれについて検討を行いました。

lingrをつかって、1週間に1回集まることにしました。時間は毎週水曜日の20:00から21:00を予定しています。
実施する内容としては、前の週における進捗の確認と、次の週に何を行うかの決定をしたいと考えていますが、もうなんか毎週それなりに進めてきて確認というのもできるか分からないので、その1時間の最初で何をやるかを決定して、1時間の間、それぞれで作業を進めるという形にしてもいいかなと思っています。これは最初の2,3回の様子をみて決めてみましょう。(というのも、自分も夏休みに作業する気が湧かないと思うし、だったら決まった時間だけ作業するという風にした方がいいのかなと思うので。)
