### ISSUE TITLE
手書きの認識

### ISSUE THREAD

**Issue by cloverrose** [android-spa-titech/HQTP#9]
黒板のわからなかったところを丸く囲ったり、文字を書いたりするときに手書きをストレスが少なく認識できる
マイルストーンはどこに入れればいいのかわかりませんでした

**Comment by draftcode** [comment]
どの段階で、どの機能を実装するのかは、また揃った時に検討してみましょう。
それまではマイルストーンに関しては意識しなくでも良いと思います。

**Comment by draftcode** [comment]
手書きの認識については、もしかしたらスコープ範囲外になるかもしれません。将来的に付けたい機能というのをどこかにまとめておくのは必要であるので、要求仕様につけておくとよいかなと思います。というかつけました。整理のためにCloseしますね。
