### ISSUE TITLE
メイン画面からバックボタンを押すとホーム画面に戻らずにログイン画面になる

### ISSUE THREAD

**Issue by draftcode** [android-spa-titech/HQTP#93]
メイン画面からバックボタンを押した後は、ログイン画面に戻らずに端末のホーム画面に戻らずに、ログイン画面に遷移してしまう。

**Comment by draftcode** [comment]
startActivityをするときに、IntentのflagにFLAG_ACTIVITY_NO_HISTORYを付けたり、FLAG_ACTIVITY_CLEAR_TOPを付けたり、AndroidManifestにnoHistoryをtrueにしたりすると良いようです。

**Comment by ide-an** [comment]
#152 で実装済みなのでcloseします
